// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Chassis.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Chassis::Chassis() : Subsystem("Chassis") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	gyroscope = RobotMap::chassisGyroscope;
	leftFrontCtrl = RobotMap::chassisLeftFrontCtrl;
	leftRearCtrl = RobotMap::chassisLeftRearCtrl;
	rightFrontCtrl = RobotMap::chassisRightFrontCtrl;
	rightRearCtrl = RobotMap::chassisRightRearCtrl;
	driveSystem = RobotMap::chassisDriveSystem;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Chassis::InitDefaultCommand() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.

void Chassis::Drive(float x, float y, float rotation) {
	driveSystem->MecanumDrive_Cartesian(x,y,rotation);
}
void Chassis::Stop() {
	Drive(0,0,0);
}
float Chassis::GetGyroAngle() {
	return gyroscope->GetAngle();
}
