// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LEDSTRIP_H
#define LEDSTRIP_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class LedStrip: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DigitalOutput* pin0;
	DigitalOutput* pin1;
	DigitalOutput* pin2;
	DigitalOutput* pin3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	LedStrip();
	enum Mode {
		kOff,
		kBlue,
		kRed,
		kGreen,
		kRainbow
	};
	void Set(Mode x);
	void Set(bool first, bool second, bool third, bool fourth);
	void InitDefaultCommand();
};

#endif
