// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "LedStrip.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

LedStrip::LedStrip() : Subsystem("LedStrip") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	pin0 = RobotMap::ledStripPin0;
	pin1 = RobotMap::ledStripPin1;
	pin2 = RobotMap::ledStripPin2;
	pin3 = RobotMap::ledStripPin3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void LedStrip::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void LedStrip::Set(bool first, bool second, bool third, bool fourth) {
	pin0->Set(first);
	pin1->Set(second);
	pin2->Set(third);
	pin3->Set(fourth);
}
void LedStrip::Set(enum Mode x) {
	if (x == Mode::kOff) Set(0,0,0,0);
	if (x == Mode::kRed) Set(1,0,0,0);
	if (x == Mode::kGreen) Set(0,1,0,0);
	if (x == Mode::kBlue) Set(1,1,0,0);
	if (x == Mode::kRainbow) Set(0,0,1,0);
}
