// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFTER_H
#define LIFTER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class Lifter: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	bool lastState;
	bool curState;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* winch;
	DigitalInput* hallEffectSensor;
	DigitalInput* bottomSwitch;
	Relay* spineLights;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Lifter();
	void Raise();
	void Lower();
	void Stop();
	void ResetLevels();
	int Levels;
	bool stopAtBottom;
	void Set(float x);
	void UpdateLevel();
	bool MagnetHit();
	bool BottomHit();
	void SetLightOn();
	void SetLightOff();
	void InitDefaultCommand();
	float speed;
};

#endif
