// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#ifndef AUTOTOTECONTAINERSTACK_H
#define AUTOTOTECONTAINERSTACK_H

#include "Commands/CommandGroup.h"


//Used commands
#include "Grab.h"
#include "Release.h"
#include "LowerOne.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class AutoToteContainerStack: public CommandGroup {
public:	
	float releasePause;
	float toContainerSpeed;
	float toContainerTime;
	float grabPause;
	float liftContainerTime;
	float liftContainerSpeed;
	float strafeToToteSpeed;
	float strafeToToteTime;
	float backupToToteSpeed;
	float backupToToteTime;
	float lowerToStackSpeed;
	float lowerToStackTime;
	AutoToteContainerStack();
};

#endif
