// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "GrabContainerAndBackup.h"
#include "Release.h"
#include "DriveForTime.h"
#include "Grab.h"
#include "../Robot.h"
#include "PauseX.h"
GrabContainerAndBackup::GrabContainerAndBackup() {
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	AddSequential(new Release());
	AddSequential(new PauseX(1));
	AddSequential(new DriveForTime(0,-0.5,0,.4)); //Drive To Container;
	AddSequential(new Grab());
	AddSequential(new PauseX(1));
	AddSequential(new DriveForTime(0,0.5,0,1.9));
	AddSequential(new DriveForTime(0,0,-0.5,1));
}
