// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "LifterWithJoystick.h"

LifterWithJoystick::LifterWithJoystick() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::lifter);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	value = 0;
}

// Called just before this Command runs the first time
void LifterWithJoystick::Initialize() {
	value = 0;
	Robot::lifter->Stop();
}

// Called repeatedly when this Command is scheduled to run
void LifterWithJoystick::Execute() {
	value = Robot::oi->getLifterAxis();
	Robot::lifter->Set(value);

	if (value >= 0.5 || value <= -0.5)  {
		Robot::lifter->SetLightOn();
		Robot::grabber->airCompressor->Stop();
	}
	else  {
		Robot::lifter->SetLightOff();
		Robot::grabber->airCompressor->Start();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool LifterWithJoystick::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void LifterWithJoystick::End() {
	Robot::lifter->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void LifterWithJoystick::Interrupted() {
	End();
}
