// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoToteContainerStack.h"
#include "Commands/DoNothingAuto.h"
#include "Commands/DriveForTime.h"
#include "Commands/DriveWithJoysticks.h"
#include "Commands/Grab.h"
#include "Commands/GrabContainerAndBackup.h"
#include "Commands/LassoIn.h"
#include "Commands/LassoOut.h"
#include "Commands/Lift.h"
#include "Commands/LiftByX.h"
#include "Commands/LiftForTime.h"
#include "Commands/LiftOne.h"
#include "Commands/LifterGoToX.h"
#include "Commands/LifterWithJoystick.h"
#include "Commands/Lower.h"
#include "Commands/LowerOne.h"
#include "Commands/LowerToBottom.h"
#include "Commands/MoveForwardAndTurn.h"
#include "Commands/PauseX.h"
#include "Commands/Release.h"
#include "Commands/TestAll.h"
#include "Commands/ToggleGrabber.h"
#include "Commands/ToggleUsingLifterLimit.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	stickRight = new Joystick(1);
	
	stickCenter = new Joystick(2);
	
	stickLeft = new Joystick(0);
	
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("DoNothingAuto", new DoNothingAuto());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	//Joystick buttons
	toggleButton = new JoystickButton(stickRight, 1);
	toggleButton->WhenPressed(new ToggleGrabber());

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getStickRight() {
	return stickRight;
}

Joystick* OI::getStickCenter() {
	return stickCenter;
}

Joystick* OI::getStickLeft() {
	return stickLeft;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
float OI::getDriveX() {
	return stickLeft->GetX();
}

float OI::getDriveY() {
	return stickLeft->GetY();
}
float OI::getDriveRotation() {
	return stickCenter->GetX();
}
float OI::getLifterAxis() {
	return stickRight->GetY();
}
bool OI::getBottomToggleButton() {
	return stickRight->GetRawButton(9);
}
bool OI::getSonicButton() {
	return stickLeft->GetRawButton(6) && stickLeft->GetRawButton(7);
}
bool OI::getSonicDisable() {
	return DriverStation::GetInstance()->IsDisabled() || stickLeft->GetRawButton(6) || stickLeft->GetRawButton(7);
}
