// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"

#include "Commands/Command.h"
#include "Commands/DriveWithJoysticks.h"
#include "Commands/LifterWithJoystick.h"
#include "Commands/MoveForwardAndTurn.h"
#include "Commands/GrabContainerAndBackup.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Subsystems/Chassis.h"
#include "Subsystems/Grabber.h"
#include "Subsystems/Lasso.h"
#include "Subsystems/LedStrip.h"
#include "Subsystems/Lifter.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "OI.h"

class Robot : public IterativeRobot {
public:
	Command* autonomousCommand;
	Command* driveWithJoysticks;
	Command* lifterWithJoystick;

	static OI *oi;
	LiveWindow *lw;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static Chassis* chassis;
	static LedStrip* ledStrip;
	static Grabber* grabber;
	static Lifter* lifter;
	static Lasso* lasso;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestInit();
	virtual void TestPeriodic();

	SendableChooser* autoChooser;
};
#endif
