// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static Gyro* chassisGyroscope;
	static SpeedController* chassisLeftFrontCtrl;
	static SpeedController* chassisLeftRearCtrl;
	static SpeedController* chassisRightFrontCtrl;
	static SpeedController* chassisRightRearCtrl;
	static RobotDrive* chassisDriveSystem;
	static DigitalOutput* ledStripPin0;
	static DigitalOutput* ledStripPin1;
	static DigitalOutput* ledStripPin2;
	static DigitalOutput* ledStripPin3;
	static Compressor* grabberAirCompressor;
	static DoubleSolenoid* grabberGrabberSolenoid;
	static SpeedController* lifterWinch;
	static DigitalInput* lifterHallEffectSensor;
	static DigitalInput* lifterBottomSwitch;
	static Relay* lifterSpineLights;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
	static PowerDistributionPanel* PDP;
	static BuiltInAccelerometer* BIA;

};
#endif
